#pragma once

#define PAGE_SHIFT 12
#define PAGE_SIZE (1 << PAGE_SHIFT)
#define PAGE_MASK (~(PAGE_SIZE - 1))

#define KERNEL_VIRTUAL_ADDRESS 0xFFFFFFFF80000000

#define KERNEL_PHYSICAL_ADDRESS 0x100000
#define KERNEL_START (KERNEL_VIRTUAL_ADDRESS + KERNEL_PHYSICAL_ADDRESS)
